config/routes.rb
Rails.application.routes.draw do

  devise_for :users,
   controllers: {
     omniauth_callbacks: "users/omniauth_callbacks"
   },
   path: "",
   path_names: {
     sign_in: "login",
     sign_out: "logout",
     sign_up: "signup"
   }

  root "feed#index"
  get "discover", to: "feed#show_discover"

  resources :users, only: [:show, :edit, :update, :destroy] do
    resources :photos, except: [:index], shallow: true
    resources :albums, except: [:index], shallow: true
    resources :followers, only: [:create], controller: "follows"
    resources :followings, only: [:create], controller: "follows"

    delete "unfollow/:following_id", to: "follows#destroy", as: :unfollow
  end

  resources :likes, only: [:create, :destroy]

  namespace :admin do
    root "photos#index"
    resources :photos, only: [:index, :edit, :update, :destroy]
    resources :albums, only: [:index, :edit, :update, :destroy]
    resources :users, only: [:index, :edit, :update, :destroy]
  end
  get "up" => "rails/health#show", as: :rails_health_check
end

app/models/photo.rb
class Photo < ApplicationRecord
  mount_uploader :image, PhotoUploader
  scope :public_m, -> { where(sharing_mode: :public_mode) }

  belongs_to :user

  enum :sharing_mode, { public_mode: 0, private_mode: 1 }

  has_many :likes, as: :likeable, dependent: :destroy
  has_many :album_photos, dependent: :destroy
  has_many :albums, through: :album_photos

  validates :image, presence: true, on: :create
  validates :sharing_mode, presence: true
  validates :description, presence: true
  validates :title, presence: true
end

app/controllers/admin/photos_controller.rb
# frozen_string_literal: true

module Admin
  class PhotosController < ApplicationController
    ITEMS_PER_PAGE = 40

    include AdminMethods

    load_and_authorize_resource
    before_action :get_photo, only: [:edit, :update, :destroy]

    def index
      @photos = Photo.page(params[:page]).per(ITEMS_PER_PAGE)
    end

    def edit
    end

    def update
      if @photo.update(photo_params)
        redirect_to admin_photos_path, notice: "Photo was successfully updated!"
      else
        render :edit, status: :unprocessable_entity
      end
    end

    def destroy
      if @photo.destroy
        redirect_to admin_photos_path, notice: "Delete photo successfully!"
      else
        render :edit, status: :unprocessable_entity
      end
    end

    private

    def photo_params
      params.require(:photo).permit(:title, :description, :sharing_mode, :image)
    end

    def get_photo
      @photo = Photo.find(params[:id])
    end
  end
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  load_and_authorize_resource
  before_action :get_photo, only: [:edit, :update, :destroy]

  def index

  end

  def new
    @photo = Photo.new
    @user_id = params[:user_id]
  end

  def create
    @user = User.find(params[:user_id])
    @photo = @user.photos.new(photo_params)
    if @photo.save
      redirect_to user_path(current_user.id), notice: "Create photo successfully!"
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
  end

  def update

    if @photo.update(photo_params)
      redirect_to user_path(current_user.id), notice: "Edit photo successfully!"
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    if @photo.destroy
      redirect_to user_path(current_user.id), notice: "Delete photo successfully!"
    else
      render :edit, status: :unprocessable_entity
    end
  end

  private

  def photo_params
    params.require(:photo).permit(:title, :description, :sharing_mode, :image)
  end

  def get_photo
    @photo = Photo.find(params[:id])
  end
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/views/admin/photos/edit.html.erb
<div class="p-4 m-4 w-100" style="min-height: 90vh;background: var(--bs-secondary-bg);">
  <div class="d-flex align-items-center justify-content-between">
    <h5 class="font-weight-bold lh-1 m-0">Edit photo</h5>
    <%= link_to "Back", request.referer, class: "btn btn-primary" %>
  </div>
  <%= form_with model: @photo, url: admin_photo_path(@photo), method: :patch, html: { enctype:
                                                                                            "multipart/form-data" } do |f| %>
    <div class="row mb-3">
      <div class="col-md-6">
        <%= f.label :title, "Title", class: "form-label" %>
        <%= f.text_field :title, value: @photo.title, class: "form-control #{'is-invalid' if @photo.errors[:title].any?}" %>
        <% @photo.errors[:title].each do |error| %>
          <div class="invalid-feedback">
            <%= error %>
          </div>
        <% end %>
      </div>
      <div class="col-md-6">
        <%= f.label :description, "Description", class: "form-label" %>
        <%= f.text_area :description, value: @photo.description, class: "form-control #{'is-invalid' if @photo
          .errors[:description].any?}", rows: 3 %>
        <% @photo.errors[:description].each do |error| %>
          <div class="invalid-feedback">
            <%= error %>
          </div>
        <% end %>
      </div>
    </div>
    <div class="mb-3 col-md-4">
      <%= f.label :sharing_mode, "Sharing mode", class: "form-label" %>
      <%= f.select :sharing_mode, Photo.sharing_modes.keys.map { |mode| [mode.titleize, mode] }, { selected: @photo.sharing_mode }, class: "form-select" %>
    </div>
    <div class="mb-4">
      <%= f.label :image, "Upload Photo", class: "form-label d-block" %>
      <label for="image-upload" class="border border-secondary border-dashed d-flex align-items-center justify-content-center position-relative rounded overflow-hidden" style="width: 150px; height: 150px;">

        <%= image_tag "#{@photo.image.url}", alt: "", class: "w-100 h-100 object-fit-cover", id:
          'pre-image-preview' %>
        <i class="fa-solid fa-xmark close-icon" id="close-icon"></i>

        <span class="fs-1 text-muted d-none" id="plus-icon">+</span>
        <%= f.file_field :image, class: "d-none", id: "image-upload", style: "pointer-events: none" %>

      </label>
    </div>
    <%= f.submit "Save", class: "btn btn-success" %>
  <% end %>
  <%= form_with model: @photo, url: admin_photo_path(@photo), method: :delete do |form| %>
    <button type="button" class="btn btn-danger delete-button" data-bs-toggle="modal"
            data-bs-target="#deletePhotoModal">
      <i class="fa-regular fa-trash-can"></i>
      Delete
    </button>
    <!-- Modal -->
    <div class="modal fade" id="deletePhotoModal" tabindex="-1" aria-labelledby="deletePhotoModalLabel"
         aria-hidden="true">
      <div class="modal-dialog">
        <div class="modal-content">
          <div class="modal-header">
            <h1 class="modal-title fs-5" id="deletePhotoModalLabel">Warning!</h1>
            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
          </div>
          <div class="modal-body">
            Are you sure to delete this photo?
          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
            <%= form.submit "Delete", class: "btn btn-danger" %>
          </div>
        </div>
      </div>
    </div>
  <% end %>
</div>

<style>
    .delete-button {
        position: relative;
        top: -38px;
        left: 120px;
    }
    .close-icon {
        position: absolute;
        top: 5px;
        right: 5px;
        font-size: 1.5rem;
        cursor: pointer;
    }
</style>

app/views/admin/photos/index.html.erb
<div class="p-4 m-4 w-100" style="min-height: 90vh; background: var(--bs-secondary-bg);">
  <div class="admin-photos">
    <% @photos.each do |photo| %>
      <div class="admin-photos__item">
        <%= image_tag "#{photo.image}", alt: "" %>
        <div class="d-flex align-items-center justify-content-center admin-photos__item--title w-100">
          <span><%= photo.title %></span>
          <%= link_to edit_admin_photo_path(photo), class: "text-white" do %>
            <i class="fa-regular fa-pen-to-square"></i>
          <% end %>
        </div>
      </div>
    <% end %>
  </div>
  <div class="d-flex align-items-center justify-content-center">
    <%= paginate @photos %>
  </div>
</div>