config/routes.rb
Rails.application.routes.draw do

  devise_for :users,
   controllers: {
     omniauth_callbacks: "users/omniauth_callbacks"
   },
   path: "",
   path_names: {
     sign_in: "login",
     sign_out: "logout",
     sign_up: "signup"
   }

  root "feed#index"
  get "discover", to: "feed#show_discover"

  resources :users, only: [:show, :edit, :update, :destroy] do
    resources :photos, except: [:index], shallow: true
    resources :albums, except: [:index], shallow: true
    resources :followers, only: [:create], controller: "follows"
    resources :followings, only: [:create], controller: "follows"

    delete "unfollow/:following_id", to: "follows#destroy", as: :unfollow
  end

  resources :likes, only: [:create, :destroy]

  namespace :admin do
    root "photos#index"
    resources :photos, only: [:index, :edit, :update, :destroy]
    resources :albums, only: [:index, :edit, :update, :destroy]
    resources :users, only: [:index, :edit, :update, :destroy]
  end
  get "up" => "rails/health#show", as: :rails_health_check
end

app/models/user.rb
class User < ApplicationRecord
  # Devise modules
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable,
         :omniauthable, omniauth_providers: [:google_oauth2, :facebook]

  def active_for_authentication?
    super && status != "inactive"
  end
  def self.from_omniauth(auth)
    User.create(
      email: auth.info.email,
      first_name: auth.info.first_name,
      last_name: auth.info.last_name,
      provider: auth.provider,
      uid: auth.uid,
      password: Devise.friendly_token[0, 20]
    )
  end

  # CarrierWave + Cloudinary
  mount_uploader :avatar, AvatarUploader

  enum :role, { guest: 0, user: 1, admin: 2 }
  enum :status, { active: 0, inactive: 1 }

  validates :first_name, presence: true, length: { maximum: 25 }
  validates :last_name, presence: true, length: { maximum: 25 }

  has_many :photos, dependent: :destroy
  has_many :albums, dependent: :destroy

  has_many :likes, dependent: :destroy

  has_many :active_follows, class_name: "Follow", foreign_key: :follower_id, dependent: :destroy
  has_many :followings, through: :active_follows, source: :following

  has_many :passive_follows, class_name: "Follow", foreign_key: :following_id, dependent: :destroy
  has_many :followers, through: :passive_follows, source: :follower

end

app/controllers/admin/users_controller.rb
# frozen_string_literal: true

module Admin
  class UsersController < ApplicationController
    ITEMS_PER_PAGE = 20

    include AdminMethods

    load_and_authorize_resource
    before_action :get_user, only: [:edit, :update, :destroy]

    def index
      @users = User.page(params[:page]).per(ITEMS_PER_PAGE)
    end

    def edit
    end

    def update
      @user.skip_reconfirmation!
      old_status = @user.status
      form_type = params[:form_type]
      if form_type == "avatar"
        if @user.update(avatar: params[:user][:avatar])
          redirect_to admin_users_path, notice: "Avatar was successfully updated."
        else
          render :edit, status: :unprocessable_entity
        end
        return
      end
      if @user.update(user_params)
        if old_status == "active" && user_params[:status] == "inactive"
          UserMailer.warning_inactive_mail(@user).deliver_now
        end
        redirect_to admin_users_path, notice: "User was successfully updated."
      else
        render :edit, status: :unprocessable_entity
      end
    end

    def destroy
      if @user.destroy
        redirect_to admin_users_path, notice: "Delete user successfully!"
      else
        render :edit, status: :unprocessable_entity
      end
    end

    private

    def user_params
      params.require(:user).permit(:avatar, :first_name, :last_name, :email, :password, :password_confirmation, :status)
    end

    def get_user
      @user = User.find(params[:id])
    end
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def google_oauth2
    auth = request.env["omniauth.auth"]
    action_type = session.delete("oauth_action_type")

    @user = User.find_by(email: auth.info.email)

    if action_type == "login"
      if @user
        sign_in_and_redirect @user, event: :authentication
        set_flash_message(:notice, :success, kind: "Google") if is_navigational_format?
      else
        redirect_to new_user_session_path, alert: "Tài khoản chưa được đăng ký. Vui lòng đăng ký trước."
      end

    elsif action_type == "signup"
      if @user
        redirect_to new_user_session_path, alert: "Email đã tồn tại. Vui lòng đăng nhập."
      else
        @user = User.from_omniauth(auth)
        if @user.persisted?
          sign_in_and_redirect @user, event: :authentication
          set_flash_message(:notice, :success, kind: "Google") if is_navigational_format?
        else
          session["devise.google_data"] = auth.except(:extra)
          redirect_to new_user_registration_url, alert: "Không thể tạo tài khoản."
        end
      end

    else
      # fallback: login/signup tự động nếu không có session
      @user = User.from_omniauth(auth)

      if @user.persisted?
        sign_in_and_redirect @user, event: :authentication
        set_flash_message(:notice, :success, kind: "Google") if is_navigational_format?
      else
        session["devise.google_data"] = auth.except(:extra)
        redirect_to new_user_registration_url
      end
    end
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  load_and_authorize_resource
  before_action :reject_admin_access, only: [:edit, :update]

  def show
    @param_user_id = params[:id]
    @user = User.includes(:photos, :albums, :followings, :followers).find(params[:id])
    @tab = params[:tab] || "photos"
    @items = []

    case @tab
    when "photos"
      @items = @user.photos.public_m
      if current_user.id == @param_user_id.to_i
        @items = @user.photos
      end
    when "albums"
      @items = @user.albums.public_m
      if current_user.id == @param_user_id.to_i
        @items = @user.albums
      end
    when "followers"
      @items = @user.followers.where.not(id: current_user.id)
    when "followings"
      @items = @user.followings.where.not(id: current_user.id)
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = current_user
    form_type = params[:form_type]
    if form_type == "avatar"
      if current_user.update(avatar: params[:user][:avatar])
        redirect_to user_path(current_user), notice: "Avatar was successfully updated."
      else
        render :edit, status: :unprocessable_entity
      end
      return
    end
    if form_type == "basic"
      permitted_params_1 = params.require(:user).permit(:first_name, :last_name, :email)
      if current_user.update(permitted_params_1)
        redirect_to user_path(current_user), notice: "User was successfully updated."
      else
        render :edit, status: :unprocessable_entity
      end
      return
    end

    if form_type == "password"
      permitted_params_2 = params.require(:user).permit(:current_password, :password, :password_confirmation)
      if permitted_params_2[:password].blank?
        @user.errors.add(:password, "can't be blank")
      end

      if permitted_params_2[:password_confirmation].blank?
        @user.errors.add(:password_confirmation, "can't be blank")
      end
      if @user.errors.any?
        render :edit, status: :unprocessable_entity
        return
      end
      if current_user.update_with_password(permitted_params_2)
        bypass_sign_in(current_user)
        redirect_to user_path(current_user), notice: "Password updated successfully!"
      else
        render :edit, status: :unprocessable_entity
      end
    end
  end

  private

  def reject_admin_access
    if current_user.admin?
      redirect_to root_path
    end
  end
end

app/helpers/users_helper.rb
# frozen_string_literal: true

module UsersHelper
  def is_following?(following_id)
    user =  current_user.followings.find_by(id: following_id)
    if user
      return true
    end
    false
  end
end

app/views/users/edit.html.erb
<div class="p-4 m-4 w-100" style="min-height: 90vh; background: var(--bs-secondary-bg);">
  <h5 class="font-weight-bold mb-4">Edit User Profile</h5>
  <hr>
  <div class="d-flex flex-column align-items-center mb-4">
    <%= image_tag @user.avatar.present? ? @user.avatar.url : "https://ui-avatars.com/api/?background=FFFFFF&color=3c5999&name=#{current_user
      .first_name}+#{current_user.last_name}", class: "rounded", style: "width: 120px; height: 120px; object-fit: cover;", id: 'image-preview' %>
    <%= form_with model: @user, html: { multipart: true }, method: :patch do |f| %>
      <%= hidden_field_tag :form_type, "avatar" %>
      <label class="btn rounded position-relative" style="background: rgba(255,255,255, 0.7); top: -50px; font-size: 13px;">
        <%= f.file_field :avatar, class: "form-control-file mt-2 d-none", id: 'avatar-upload' %>
        <span class="text-black">CHANGE</span>
      </label>
      <%= f.submit "Save", id: 'avatar-submit', class: "btn btn-success d-none rounded position-relative", style: "top: -50px;" %>
    <% end %>
  </div>
  <!-- Basic Info Form -->
  <div class="row">
    <div class="col-5"></div>
    <div class="col">
      <h6 class="text-primary fw-bold">Basic Information</h6>
    </div>
  </div>
  <%= form_with model: @user, method: :patch do |f| %>
    <%= hidden_field_tag :form_type, "basic" %>
    <div class="form-group row align-items-center <%= 'mb-2' unless @user.errors[:first_name].any? %>">
      <label class="col-5 text-end fw-bold" for="user_first_name">First Name</label>
      <div class="col-5">
        <%= f.text_field :first_name, class: "form-control #{'is-invalid' if @user.errors[:first_name].any?}", placeholder: "First Name" %>
      </div>
    </div>
    <div class="row">
      <div class="col-5"></div>
      <div class="col">
        <% @user.errors[:first_name].each do |error| %>
          <div class="invalid-feedback d-block mb-2">
            <%= error %>
          </div>
        <% end %>
      </div>
    </div>
    <div class="form-group row align-items-center <%= 'mb-2' unless @user.errors[:last_name].any? %>">
      <label class="col-5 text-end fw-bold">Last Name</label>
      <div class="col-5">
        <%= f.text_field :last_name, class: "form-control #{'is-invalid' if @user.errors[:last_name].any?}", placeholder:
          "Last Name" %>
      </div>
    </div>
    <div class="row">
      <div class="col-5"></div>
      <div class="col">
        <% @user.errors[:last_name].each do |error| %>
          <div class="invalid-feedback d-block mb-2">
            <%= error %>
          </div>
        <% end %>
      </div>
    </div>
    <div class="form-group row align-items-center <%= 'mb-4' unless @user.errors[:email].any? %>">
      <label class="col-5 text-end fw-bold">Email</label>
      <div class="col-5">
        <%= f.email_field :email, class: "form-control #{'is-invalid' if @user.errors[:email].any?}",
                          disabled: true, placeholder:
          "someone@example.com" %>
      </div>
    </div>
    <div class="row">
      <div class="col-5"></div>
      <div class="col">
        <% @user.errors[:email].each do |error| %>
          <div class="invalid-feedback d-block mb-4">
            <%= error %>
          </div>
        <% end %>
      </div>
    </div>
    <div class="row">
      <div class="col-5"></div>
      <div class="col">
        <%= f.submit "Save", class: "btn btn-success" %>
      </div>
    </div>
  <% end %>
  <!-- Password Form -->
  <div class="row">
    <div class="col-5"></div>
    <div class="col">
      <h6 class="text-primary font-weight-bold mt-5">Password</h6>
    </div>
  </div>
  <%= form_with model: @user, method: :patch do |f| %>
    <%= hidden_field_tag :form_type, "password" %>
    <div class="form-group row align-items-center <%= 'mb-2' unless @user.errors[:current_password].any? %>">
      <label class="col-5 text-end fw-bold">Current Password</label>
      <div class="col-5">
        <%= f.password_field :current_password, class: "form-control #{'is-invalid' if @user.errors[:current_password].any?}" %>
      </div>
    </div>
    <div class="row">
      <div class="col-5"></div>
      <div class="col">
        <% @user.errors[:current_password].each do |error| %>
          <div class="invalid-feedback d-block mb-4">
            <%= error %>
          </div>
        <% end %>
      </div>
    </div>
    <div class="form-group row align-items-center <%= 'mb-2' unless @user.errors[:password].any? %>">
      <label class="col-5 text-end fw-bold">New Password</label>
      <div class="col-5">
        <%= f.password_field :password, class: "form-control #{'is-invalid' if @user.errors[:password].any?}" %>
      </div>
    </div>
    <div class="row">
      <div class="col-5"></div>
      <div class="col">
        <% @user.errors[:password].each do |error| %>
          <div class="invalid-feedback d-block mb-4">
            <%= error %>
          </div>
        <% end %>
      </div>
    </div>
    <div class="form-group row align-items-center <%= 'mb-4' unless @user.errors[:password_confirmation].any? %>">
      <label class="col-5 text-end fw-bold">Password Confirmation</label>
      <div class="col-5">
        <%= f.password_field :password_confirmation, class: "form-control #{'is-invalid' if @user.errors[:password_confirmation].any?}" %>
      </div>
    </div>
    <div class="row">
      <div class="col-5"></div>
      <div class="col">
        <% @user.errors[:password_confirmation].each do |error| %>
          <div class="invalid-feedback d-block mb-4">
            <%= error %>
          </div>
        <% end %>
      </div>
    </div>
    <div class="row">
      <div class="col-5"></div>
      <div class="col">
        <%= f.submit "Save", class: "btn btn-success" %>
      </div>
    </div>
  <% end %>
</div>

app/views/users/show.html.erb
<div class="profile">
  <div class="profile-info">
    <div class="profile-info__avatar">
      <% if @user.avatar.present? %>
        <%= image_tag "#{@user.avatar.url}", alt: "Avatar", class: "" %>
      <% else %>
        <%= image_tag "https://ui-avatars.com/api/?background=FFFFFF&color=3c5999&name=#{@user
          .first_name}+#{@user.last_name}", alt: "Avatar" %>
      <% end %>
      <%#= image_tag "#{@user.avatar.url}", alt: "Avatar", class: "" %>
    </div>
    <div class="profile-info__content">
      <% if user_signed_in? && @param_user_id.to_i === current_user.id %>
        <%= link_to "Edit profile", edit_user_path(@user), class: "profile-info__badge--me" %>
      <% else %>
        <% if is_following?(@param_user_id) %>
          <div class="profile-info__badge"><span>following</span></div>
        <% else %>
          <%= form_with url: user_followers_path(current_user), local: true do |f| %>
            <%= hidden_field_tag :following_id, @param_user_id %>
            <%= f.button type: "submit", class: "profile-info__badge profile-info__badge--inactive" do %>
              <span>follow</span>
            <% end %>
          <% end %>
        <% end %>
      <% end %>
      <div class="profile-info__name"><%= "#{@user.first_name} #{@user.last_name}" %></div>
      <div class="profile-info__tags">
        <%= link_to user_path(@user, tab: 'photos'), class: ['profile-info__tags--item', ('profile-info__tags--item--active' if @tab == 'photos')] do %>
          <span class="fs-4">
            <% if current_user.id == @param_user_id.to_i %>
              <%= @user.photos.length %>
            <% else %>
              <%= @user.photos.public_m.length %>
            <% end %>
          </span>
          <span>PHOTOS</span>
        <% end %>
        <div class="profile-info__tags--divider"></div>
        <%= link_to user_path(@user, tab: 'albums'), class: ['profile-info__tags--item', ('profile-info__tags--item--active' if @tab == 'albums')] do %>
          <span class="fs-4">
            <% if current_user.id == @param_user_id.to_i %>
              <%= @user.albums.length %>
            <% else %>
              <%= @user.albums.public_m.length %>
            <% end %>
          </span>
          <span>ALBUMS</span>
        <% end %>
        <div class="profile-info__tags--divider"></div>
        <%= link_to user_path(@user, tab: 'followings'), class: ['profile-info__tags--item', ('profile-info__tags--item--active' if @tab == 'followings')] do %>
          <span class="fs-4">
            <%= @user.followings.length %>
          </span>
          <span>FOLLOWINGS</span>
        <% end %>
        <div class="profile-info__tags--divider"></div>
        <%= link_to user_path(@user, tab: 'followers'), class: ['profile-info__tags--item', ('profile-info__tags--item--active' if @tab == 'followers')] do %>
          <span class="fs-4">
            <%= @user.followers.length %>
          </span>
          <span>FOLLOWERS</span>
        <% end %>
      </div>
    </div>
  </div>
  <% if user_signed_in? && @param_user_id.to_i === current_user.id && @tab == 'photos' %>
    <%= link_to "Add Photo", new_user_photo_path(current_user), class: "profile-info__add-photo d-block" %>
  <% end %>
  <% if user_signed_in? && @param_user_id.to_i === current_user.id && @tab == 'albums' %>
    <%= link_to "Add Album", new_user_album_path(current_user), class: "profile-info__add-photo d-block" %>
  <% end %>
  <div class="profile-list">
    <% @items.each do |item| %>
      <% if @tab == 'photos' %>
        <div class="d-flex flex-column align-items-center justify-content-center gap-2 profile-list__item">
          <div class="position-relative">
            <%= image_tag "#{item.image}", alt: "", class: "rounded" %>
            <% if user_signed_in? && @param_user_id.to_i === current_user.id %>
              <%= link_to "EDIT", edit_photo_path(item), class: "profile-list__item--after profile-list__item--after-photos" %>
            <% end %>
            <% if item.sharing_mode == "private_mode" %>
              <i class="fa-solid fa-lock profile-list__item--lock"></i>
            <% end %>
          </div>
          <span><%= item.title %></span>
        </div>
      <% elsif @tab == 'albums' %>
        <div class="d-flex flex-column align-items-center justify-content-center gap-2 profile-list__item">
          <div class="p-3 w-100 h-100 d-flex align-items-center justify-content-center">
            <div class="position-relative first-img">
              <%= image_tag "#{item.photos[0]&.image || 'unknown-avatar.png'}", alt: "" %>
              <% if user_signed_in? && @param_user_id.to_i === current_user.id %>
                <%= link_to "EDIT", edit_album_path(item), class: "profile-list__item--after profile-list__item--after-albums" %>
              <% end %>
              <% if item.sharing_mode == "private_mode" %>
                <i class="fa-solid fa-lock profile-list__item--lock"></i>
              <% end %>
            </div>
            <%= image_tag "#{item.photos[1]&.image || 'unknown-avatar.png'}", alt: "" %>
            <%= image_tag "#{item.photos[2]&.image || 'unknown-avatar.png'}", alt: "" %>
            <div class="profile-list__item--count">
              <span class="fs-3 lh-1"><%= item.photos.length %></span>
              PHOTOS
            </div>
          </div>
          <span><%= item.title %></span>
        </div>
      <% elsif @tab == 'followings' %>
        <div class="d-flex flex-column align-items-center justify-content-center gap-2 profile-followings__item">
          <%= link_to user_path(item.id), class: "d-flex flex-column align-items-center justify-content-center gap-2" do %>
            <%= image_tag "#{item.avatar.url}", alt: "", class: "profile-followings__item--avatar" %>
            <div class="fw-bold fs-6 mb-1"><%= item.first_name %> <%= item.last_name %></div>
          <% end %>
          <div class="d-flex align-items-center justify-content-center gap-4 profile-followings__item--stat ">
            <div class="d-flex flex-column align-items-center justify-content-center ">
              <span class="fs-2 lh-1 fw-bold"><%= item.photos.length %></span>
              <span>PHOTOS</span>
            </div>
            <div class="d-flex flex-column align-items-center justify-content-center">
              <span class="fs-2 lh-1 fw-bold"><%= item.albums.length %></span>
              <span>ALBUMS</span>
            </div>
          </div>
          <% if @param_user_id.to_i == current_user.id %>
            <%= form_with url: user_unfollow_path(current_user.id, item.id), method: :delete do |f| %>
              <%= f.button type: "submit", class: "profile-info__badge profile-info__badge--inactive" do %>
                <span>unfollow</span>
              <% end %>
            <% end %>
          <% else %>
            <% if is_following?(item.id) %>
              <div class="profile-info__badge"><span>following</span></div>
            <% else %>
              <%= form_with url: user_followers_path(current_user) do |f| %>
                <%= hidden_field_tag :following_id, item.id %>
                <%= f.button type: "submit", class: "profile-info__badge profile-info__badge--inactive", data: { turbo: false } do %>
                  <span>follow</span>
                <% end %>
              <% end %>
            <% end %>
          <% end %>
        </div>
      <% else %>
        <div class="d-flex flex-column align-items-center justify-content-center gap-2 profile-followings__item">
          <%= link_to user_path(item.id), class: "d-flex flex-column align-items-center justify-content-center gap-2" do %>
            <%= image_tag "#{item.avatar.url}", alt: "", class: "profile-followings__item--avatar" %>
            <div class="fw-bold fs-6 mb-1"><%= item.first_name %> <%= item.last_name %></div>
          <% end %>
          <div class="d-flex align-items-center justify-content-center gap-4 profile-followings__item--stat ">
            <div class="d-flex flex-column align-items-center justify-content-center ">
              <span class="fs-2 lh-1 fw-bold"><%= item.photos.length %></span>
              <span>PHOTOS</span>
            </div>
            <div class="d-flex flex-column align-items-center justify-content-center">
              <span class="fs-2 lh-1 fw-bold"><%= item.albums.length %></span>
              <span>ALBUMS</span>
            </div>
          </div>
          <% if is_following?(item.id) %>
            <div class="profile-info__badge"><span>following</span></div>
          <% else %>
            <%= form_with url: user_followers_path(current_user) do |f| %>
              <%= hidden_field_tag :following_id, item.id %>
              <%= f.button type: "submit", class: "profile-info__badge profile-info__badge--inactive", data: { turbo: false } do %>
                <span>follow</span>
              <% end %>
            <% end %>
          <% end %>
        </div>
      <% end %>
    <% end %>
  </div>
</div>