config/routes.rb
Rails.application.routes.draw do

  devise_for :users,
   controllers: {
     omniauth_callbacks: "users/omniauth_callbacks"
   },
   path: "",
   path_names: {
     sign_in: "login",
     sign_out: "logout",
     sign_up: "signup"
   }

  root "feed#index"
  get "discover", to: "feed#show_discover"

  resources :users, only: [:show, :edit, :update, :destroy] do
    resources :photos, except: [:index], shallow: true
    resources :albums, except: [:index], shallow: true
    resources :followers, only: [:create], controller: "follows"
    resources :followings, only: [:create], controller: "follows"

    delete "unfollow/:following_id", to: "follows#destroy", as: :unfollow
  end

  resources :likes, only: [:create, :destroy]

  namespace :admin do
    root "photos#index"
    resources :photos, only: [:index, :edit, :update, :destroy]
    resources :albums, only: [:index, :edit, :update, :destroy]
    resources :users, only: [:index, :edit, :update, :destroy]
  end
  get "up" => "rails/health#show", as: :rails_health_check
end

app/views/shared/_header.html.erb
<header class="header">
  <div class="header__logo-search">
    <% if user_signed_in? && current_user.role == 'admin' %>
      <%= link_to "Fotobook Admin", admin_root_path, class: "header__logo" %>
    <% else %>
      <%= link_to "Fotobook", root_path, class: "header__logo" %>
    <% end %>
    <form action="" class="header__search">
      <input type="text" placeholder="Select Photo / Album" class="form-control header__search-input"/>
    </form>
  </div>
  <% if user_signed_in? %>
    <div class="header__user">
      <%= link_to user_path(current_user, tab: 'photos'), class: "header__user--info" do %>
        <div class="header__user--avatar">
          <% if current_user.avatar.present? %>
            <%= image_tag "#{current_user.avatar.url}", alt: "Avatar", class: "" %>
          <% else %>
            <%= image_tag "https://ui-avatars.com/api/?background=FFFFFF&color=3c5999&name=#{current_user
              .first_name}+#{current_user.last_name}", alt: "Avatar" %>
          <% end %>
        </div>
        <div class="text-white"><%= current_user.first_name %></div>
      <% end %>
      <%= form_with url: '/logout', method: :delete, local: true, html: { id: "logout-form", data: { turbo: false } } do %>
        <button type="button" class="header__user--logout" data-bs-toggle="modal" data-bs-target="#logoutModal">
          Logout
        </button>
        <!-- Modal -->
        <div class="modal fade" id="logoutModal" tabindex="-1" aria-labelledby="logoutModalLabel" aria-hidden="true">
          <div class="modal-dialog">
            <div class="modal-content">
              <div class="modal-header">
                <h1 class="modal-title fs-5" id="logoutModalLabel">Cảnh báo!</h1>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
              </div>
              <div class="modal-body">
                Bạn có chắc chắn muốn đăng xuất?
              </div>
              <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                <%= submit_tag "Logout", class: "btn btn-primary" %>
              </div>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  <% else %>
    <%= link_to "Login", new_user_session_path, class: "header__login" %>
  <% end %>
  <i class="fa-regular fa-moon text-white ms-5" id="mode-theme-button"></i>
</header>

app/views/shared/_pagination.html.erb
<div id="pagination" data-controller="infinite-scroll">
  <% if items.next_page %>
    <% if is_discover == true %>
      <%= link_to discover_path(tab: @tab, page: items.next_page),
                  data: { turbo_frame: "pagination", turbo_action: "append", turbo_stream: true }, class:
                    "d-flex align-items-center justify-content-center gap-2", remote: true do %>
        <span class="loader"></span>
        <span id="load-text">Tải thêm</span>
      <% end %>
    <% else %>
      <%= link_to root_path(tab: @tab, page: items.next_page),
                  data: { turbo_frame: "pagination", turbo_action: "append", turbo_stream: true }, class:
                    "d-flex align-items-center justify-content-center gap-2", remote: true do %>
        <span class="loader"></span>
        <span id="load-text">Tải thêm</span>
      <% end %>
    <% end %>
  <% else %>
    <div class="text-muted">Đã tải hết bài viết</div>
  <% end %>
</div>

app/views/shared/_sidebar-admin.html.erb
<div class="sidebar">
  <div class="sidebar-list">
    <%= link_to "Manage Photos", admin_photos_path, class: ["sidebar-list__item", ('sidebar-list__item--active' if
      side_bar_pathname?('/admin/photos') || side_bar_pathname_exact?(admin_root_path))] %>
    <%= link_to "Manage Albums", admin_albums_path, class: ["sidebar-list__item", ('sidebar-list__item--active' if side_bar_pathname?('/admin/albums'))] %>
    <%= link_to "Manage Users", admin_users_path, class: ["sidebar-list__item", ('sidebar-list__item--active' if
      side_bar_pathname?('/admin/users'))] %>
  </div>
</div>

app/views/shared/_sidebar.html.erb
<div class="sidebar">
  <div class="sidebar-list">
    <%= link_to "Feeds", root_path, class: ["sidebar-list__item", ('sidebar-list__item--active' if
      !side_bar_pathname?(discover_path) && controller_name == 'feed')] %>
    <% if user_signed_in? %>
      <%= link_to "Discover", discover_path, class: ["sidebar-list__item", ('sidebar-list__item--active' if
        side_bar_pathname?(discover_path))] %>
    <% end %>
  </div>
</div>